version: '3.7'

services:

    mongodbSupport:
        image: mongo
        container_name: mongodbSupport
        ports: 
          - '27017:27017'
        # restart: always
        environment: 
            MONGO_INITDB_DATABASE: smart-dev
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes: 
            - './data:/data'


    support-service:
        build: .
        ports: 
          - 8000:8000
        container_name: support-service
        restart: always
        volumes: 
          - './app:/app'